=== replab/replab/external/qtfm/helpfiles/xmlfiles/qtfmfunction.dtd
<!-- Document type definition for QTFM function help document -->
<!-- (c) Stephen J. Sangwine and Nicolas Le Bihan, 2008 -->
<!--                                                          -->
<!-- See the file 'readme.txt' for information about how this -->
<!-- DTD file is used.                                        -->

<!ELEMENT function (short, syntax, long, examples?, seealso?, references?)>
<!ATTLIST function name      NMTOKEN #REQUIRED
                   overload (false | true | both) "false">

<!ENTITY  reg     '&#x00AE;'>
<!ENTITY  matlab "MATLAB&reg;">
<!ELEMENT short     (#PCDATA)><!-- Short description of QTFM function. -->
<!ELEMENT syntax    (#PCDATA)><!-- Typical calling syntax. -->

<!-- Description of what the function does. -->
<!ELEMENT long      (#PCDATA | para | figure | www)*>

<!ELEMENT examples  (#PCDATA | code | precode)*><!-- Command examples. -->
<!ELEMENT para      (#PCDATA | code | italic | bold | www)*>
<!ELEMENT code      (#PCDATA)><!-- Inline code snippet -->
<!ELEMENT precode   (#PCDATA)><!-- Preformatted code-->
<!ELEMENT figure    (#PCDATA)><!-- The image filename in the helpfiles directory -->
<!ELEMENT references (reference*)>
<!ELEMENT reference (#PCDATA | italic | bold | doi | www)*>
<!ELEMENT italic    (#PCDATA)>
<!ELEMENT bold      (#PCDATA)>
<!ELEMENT doi       (#PCDATA)><!-- A hyperlink to a DOI. -->
<!ELEMENT www       (#PCDATA)><!-- A hyperlink to a website. -->

<!-- Optional section with a list of related Matlab and/or QTFM functions. -->
<!ELEMENT seealso   (#PCDATA | matlabfun | qtfmfun)*>
<!-- Ideally, the next two should be constrained to legal function names only. -->
<!ELEMENT matlabfun EMPTY>
<!ATTLIST matlabfun name NMTOKEN #REQUIRED>
<!ELEMENT qtfmfun   EMPTY>
<!ATTLIST qtfmfun   name NMTOKEN #REQUIRED alias NMTOKEN #IMPLIED>
<!--$Id: qtfmfunction.dtd 1004 2017-11-15 17:14:09Z sangwine $-->

=== replab/replab/external/qtfm/helpfiles/xmlfiles/size.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE function SYSTEM "qtfmfunction.dtd">
<function name = "size" overload = "both">
<short>Size of matrix</short>
<syntax>Y = size(X, N)</syntax>
<long>
<para>
<code>size(X)</code> returns the size of the quaternion array <code>X</code>.
</para>
<para>
<code>size(X, N)</code> returns the size of the N-th dimensions of the
quaternion array <code>X</code>.
</para>
</long>
<examples>
<precode>
>> q = randq(4,5)
 
q = 4x5 quaternion array
 
>> size(q)

ans = 4     5
</precode>
</examples>
<seealso>
<matlabfun name = "size"/>
</seealso>
</function>

<!--$Id: size.xml 1004 2017-11-15 17:14:09Z sangwine $-->

=== replab/replab/external/qtfm/helpfiles/xmlfiles/fftflip.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE function SYSTEM "qtfmfunction.dtd">
<function name = "fftflip" overload = "false">
<short>Reverse signal or spectrum.</short>
<syntax>Y = fftflip(X)</syntax>
<long>
    <para>
        <code>fftflip</code> implements a type of flip operation, in which the
        first element of the array remains unchanged and the rest reverse their order.
        Given an even length array indexed by <code>1:n</code>,
        the result is indexed <code>1 n n-1 ... 2</code>.
        An odd length array is dealt with in the same way. Expressed in terms of
        frequency coefficients of an FFT, the DC term stays put, the Nyquist term
        stays put (even length only), and the positive and negative frequency
        terms swap places.
    </para>
    <para>
If the input is a matrix, this function operates on the columns.
</para>
    <para>
        The function will work on any
        type of array, including double, so it may be used on complex arrays.
    </para>
</long>
<seealso>
<qtfmfun name = "fftflip2"/>
</seealso>
    <references>
        <reference>
        Ell, T. A., Le Bihan, N. and Sangwine, S. J.,
        <italic>Quaternion Fourier Transforms for Signal and Image Processing</italic>,
        Wiley-ISTE 2014, ISBN 978-1-84821-478-1, 140pp. See Chapter 3.
        </reference>
    </references>
</function>

<!--$Id: fftflip.xml 1004 2017-11-15 17:14:09Z sangwine $-->

=== replab/replab/external/qtfm/helpfiles/xmlfiles/orthogonal.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE function SYSTEM "qtfmfunction.dtd">
<function name = "orthogonal" overload = "false">
<short>Construct unit pure quaternions orthogonal to elements of a pure quaternion array</short>
<syntax>U = orthogonal(V, W)</syntax>
<long>
    <para>
        <code>orthogonal(V, W)</code> constructs and returns an array of unit pure quaternions
        each orthogonal to the corresponding element of <code>V</code>, and <code>W</code> if given.
        <code>V</code> and <code>W</code> must be pure quaternions, but need not have unit modulus.
        Elements of <code>W</code> need not be orthogonal to the corresponding elements of <code>V</code>,
        but they must not be parallel.
    </para>
    <para>
        Either or both of <code>V</code> or <code>W</code> may be a scalar,
        in which case, it is treated as if the same size as the other.
    </para>
    <para>
        The function works for the complex quaternion case as well as for
        real quaternions.
    </para>
</long>
<examples>
<precode>
>> orthogonal(qi, qj)
 
ans = 0 * I + 0 * J + 1 * K

>> A = randv(3);
>> B = orthogonal(A, quaternion(1,0,1));
>> scalar_product(A, B)

ans =

   1.0e-16 *

         0    0.5551   -0.0694
    0.0520         0         0
         0    0.5551   -0.5551
</precode>
</examples>
</function>

<!--$Id: orthogonal.xml 1004 2017-11-15 17:14:09Z sangwine $-->

=== replab/replab/external/qtfm/helpfiles/xmlfiles/permute.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE function SYSTEM "qtfmfunction.dtd">
<function name = "permute" overload = "true">
<short>Permute dimensions of N-D array</short>
<syntax>Y = permute(X, order)</syntax>
<long>
<para>
<code>permute(X, order)</code> permutes the dimensions of an N-D array.
It accepts the same arguments as the overloaded
&matlab; function and is implemented by calling the overloaded function on
each component of <code>X</code>.
</para>
</long>
<examples>
</examples>
<seealso>
<matlabfun name = "permute"/>
<qtfmfun name = "ipermute"/>
</seealso>
</function>
<!--$Id: permute.xml 1004 2017-11-15 17:14:09Z sangwine $-->

=== replab/replab/external/qtfm/helpfiles/xmlfiles/angle.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE function SYSTEM "qtfmfunction.dtd">
<function name = "angle" overload = "both">
<short>Angle of a quaternion in polar form</short>
<syntax>θ = angle(q, a)</syntax>
<long>
<para>
<code>angle(X)</code> computes the angle of a quaternion in polar form. The
polar form of a quaternion is q = A exp(μθ) where A is a real or complex
modulus, μ is a unit pure quaternion, and θ is an angle. It is θ that is
computed by this function.
</para>
<para>
The second parameter is optional. If omitted, the result will always be
in the range (0, π), that is, the quaternion q is regarded as being in
the upper half of a complex plane defined by the axis of q. A reference
unit vector defining the direction of the positive imaginary axis of q
may be supplied as the second parameter, in which case the result may
be in the full range from -π to +π. This reference unit vector is used
to define the north pole of a hemisphere of 3-space, so that if the axis
of q lies in this hemisphere, the angle is in the range (0,π). If the
axis of q lies in the other (southern) hemisphere, then the angle
returned will lie in (π, 2*π).
</para>
<para>
The optional argument must be either the same size as q or be a scalar
(in which case the same value is used for all elements of q).
</para>
</long>
<examples>
<precode>
>> angle(randq(2))

ans =

    1.8062    1.5062
    2.2535    1.9501
</precode>
</examples>
<seealso>
<matlabfun name = "angle"/>
<qtfmfun name = "axis"/>
</seealso>
</function>

<!--$Id: angle.xml 1004 2017-11-15 17:14:09Z sangwine $-->

=== replab/replab/external/qtfm/helpfiles/xmlfiles/atan.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE function SYSTEM "qtfmfunction.dtd">
<function name = "atan" overload = "true">
<short>Inverse tangent.</short>
<syntax>Y = atan(X)</syntax>
<long>
<para>
<code>atan(X)</code> computes the inverse tangent of its argument, which
must be a real quaternion (<code>atan</code> is not yet implemented for
complexified quaternions).
</para>
<para>
This function is computed using the Matlab® function of the same name by
first computing an isomorphic complex number. The result is then assigned
the same quaternion axis as the original argument.
</para>
</long>
<examples>
<precode>
>> atan(qi + qj + qk)

ans = 1.571 + 0.3802 * I + 0.3802 * J + 0.3802 * K 
</precode>
</examples>
<seealso>
<matlabfun name = "atan"/>
<qtfmfun name = "tan"/>
</seealso>
</function>
<!--$Id: atan.xml 1004 2017-11-15 17:14:09Z sangwine $-->

=== replab/replab/external/qtfm/helpfiles/xmlfiles/isinf.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE function SYSTEM "qtfmfunction.dtd">
<function name = "isinf" overload = "both">
<short>Array elements that are infinite</short>
<syntax>TF = isinf(X)</syntax>
<long>
<para>
<code>isinf(X)</code> returns logical 1 (<code>true</code>) for array
elements that contain at least one quaternion/octonion component which is
<code>infinite</code>. It returns logical
0 (<code>false</code>) at array positions where all quaternion/octonion
components are <code>finite</code>.
</para>
</long>
<seealso>
<matlabfun name = "isinf"/>
<qtfmfun name = "isfinite"/>
</seealso>
</function>

<!--$Id: isinf.xml 1004 2017-11-15 17:14:09Z sangwine $-->

=== replab/replab/external/qtfm/helpfiles/xmlfiles/cos.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE function SYSTEM "qtfmfunction.dtd">
<function name = "cos" overload = "true">
<short>Cosine</short>
<syntax>Y = cos(X)</syntax>
<long>
<para>
<code>cos(X)</code> computes the cosine of the quaternion argument <code>X</code>
which may be a complexified quaternion.
</para>
</long>
<examples>
<precode>
>> cos(1 + qi)
 
ans = 0.8337 - 0.9889 * I + 0 * J + 0 * K
</precode>
</examples>
<seealso>
<matlabfun name = "cos"/>
<qtfmfun name = "sin"/>
</seealso>
</function>

<!--$Id: cos.xml 1004 2017-11-15 17:14:09Z sangwine $-->
