=== replab/replab/external/qtfm/helpfiles/xmlfiles/qtfmfunction.dtd
<!-- Document type definition for QTFM function help document -->
<!-- (c) Stephen J. Sangwine and Nicolas Le Bihan, 2008 -->
<!--                                                          -->
<!-- See the file 'readme.txt' for information about how this -->
<!-- DTD file is used.                                        -->

<!ELEMENT function (short, syntax, long, examples?, seealso?, references?)>
<!ATTLIST function name      NMTOKEN #REQUIRED
                   overload (false | true | both) "false">

<!ENTITY  reg     '&#x00AE;'>
<!ENTITY  matlab "MATLAB&reg;">
<!ELEMENT short     (#PCDATA)><!-- Short description of QTFM function. -->
<!ELEMENT syntax    (#PCDATA)><!-- Typical calling syntax. -->

<!-- Description of what the function does. -->
<!ELEMENT long      (#PCDATA | para | figure | www)*>

<!ELEMENT examples  (#PCDATA | code | precode)*><!-- Command examples. -->
<!ELEMENT para      (#PCDATA | code | italic | bold | www)*>
<!ELEMENT code      (#PCDATA)><!-- Inline code snippet -->
<!ELEMENT precode   (#PCDATA)><!-- Preformatted code-->
<!ELEMENT figure    (#PCDATA)><!-- The image filename in the helpfiles directory -->
<!ELEMENT references (reference*)>
<!ELEMENT reference (#PCDATA | italic | bold | doi | www)*>
<!ELEMENT italic    (#PCDATA)>
<!ELEMENT bold      (#PCDATA)>
<!ELEMENT doi       (#PCDATA)><!-- A hyperlink to a DOI. -->
<!ELEMENT www       (#PCDATA)><!-- A hyperlink to a website. -->

<!-- Optional section with a list of related Matlab and/or QTFM functions. -->
<!ELEMENT seealso   (#PCDATA | matlabfun | qtfmfun)*>
<!-- Ideally, the next two should be constrained to legal function names only. -->
<!ELEMENT matlabfun EMPTY>
<!ATTLIST matlabfun name NMTOKEN #REQUIRED>
<!ELEMENT qtfmfun   EMPTY>
<!ATTLIST qtfmfun   name NMTOKEN #REQUIRED alias NMTOKEN #IMPLIED>
<!--$Id: qtfmfunction.dtd 1004 2017-11-15 17:14:09Z sangwine $-->

=== replab/replab/external/qtfm/helpfiles/xmlfiles/imreadq.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE function SYSTEM "qtfmfunction.dtd">
<function name = "imreadq" overload = "false">
<short>Read an image file into a quaternion array.</short>
<syntax>A = imreadq(filename, fmt)</syntax>
<long>
    <para>
        <code>imreadq</code> reads an image file into a pure
        quaternion array. It supports the same parameter profiles as the &matlab;
        function <code>imread</code>, but returns a quaternion
        array with elements of type <code>uint8</code> or
        <code>uint16</code> depending on whether the image file contained
        8-bit or 16-bit samples.
    </para>
    <para>
        The function supports only RGB images, and returns a pure quaternion array.
        The parameter profiles supported are the same as for the &matlab;
        function <code>imread</code> but not all parameter profiles may
        make sense. This is because the &matlab; function is used to perform
        the file read, and the data is then converted into pure quaternion format.
        No scaling or casting of the component values is done.
    </para>
    <para>
        The function supports the same image file types as the &matlab; function <code>imread</code>.
    </para>
</long>
<examples>
<precode>
>> A = imreadq('random.png')
 
A = 128x128 pure quaternion array with uint8 components
</precode>
</examples>
<seealso>
<matlabfun name = "imread"/>
<qtfmfun name = "imwrite"/>
<qtfmfun name = "image"/>
</seealso>
</function>

<!--$Id: imreadq.xml 1004 2017-11-15 17:14:09Z sangwine $-->

=== replab/replab/external/qtfm/helpfiles/xmlfiles/mrdivide.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE function SYSTEM "qtfmfunction.dtd">
<function name = "mrdivide" overload = "both">
<short>/ Matrix right divide</short>
<syntax>Y = A/B</syntax>
<long>
<para>
<code>A/B</code> computes matrix right divide. It is implemented for
quaternion and octonion arrays only for the case where <code>B</code> is a scalar
(that is a single quaternion/octonion or numeric value). In this case, the
result is exactly the same as that given by the elementwise right
divide (<code>./</code>). The reason for implementing this
function is that some &matlab; code uses <code>/</code> when <code>./</code>
should have been used. The existence of this function in the &qtfm;
toolbox makes it possible for &matlab; functions to work on quaternion/octonion
arrays if all other necessary functions are overloaded. An example is the &matlab;
<code>cov</code> function.
</para>
</long>
<seealso>
<matlabfun name = "mrdivide"/>
<qtfmfun name = "rdivide"/>
</seealso>
</function>

<!--$Id: mrdivide.xml 1004 2017-11-15 17:14:09Z sangwine $-->

=== replab/replab/external/qtfm/helpfiles/xmlfiles/orthonormal_basis.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE function SYSTEM "qtfmfunction.dtd">
<function name = "orthonormal_basis" overload = "false">
<short>Construct orthonormal basis</short>
<syntax>B = orthonormal_basis(V, W)</syntax>
<long>
<para>
Creates an orthonormal basis from a pure quaternion V,
and an optional pure quaternion W, which need not be perpendicular to V,
but must not be parallel.
</para>
<para>
The result is represented as a 3×3 orthogonal matrix, which may be
complex if V and/or W are complex pure quaternions.
</para>
</long>
<examples>
<precode>
>> orthonormal_basis(qi + qj, qk + qi)

ans =

    0.7071    0.7071         0
    0.5774   -0.5774   -0.5774
   -0.4082    0.4082   -0.8165

>> ans * ans'

ans =

    1.0000    0.0000   -0.0000
    0.0000    1.0000   -0.0000
   -0.0000   -0.0000    1.0000
</precode>
</examples>
<seealso>
<qtfmfun name = "change_basis"/>
</seealso>
</function>

<!--$Id: orthonormal_basis.xml 1004 2017-11-15 17:14:09Z sangwine $-->

=== replab/replab/external/qtfm/helpfiles/xmlfiles/quiver3.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE function SYSTEM "qtfmfunction.dtd">
<function name = "quiver3" overload = "true">
<short>3D quiver plot from quaternion array.</short>
<syntax>h = quiver3(o, p, varargin)</syntax>
<long>
    <para>
        <code>quiver3</code> plots a 3D quiver plot of elements in a 
        pure quaternion array. It supports the same parameter profiles as
        the &matlab; function of the same name, except that the first three
        or six
        parameters <code>(X, Y, Z, U, V, W)</code> are replaced by a one or
        two
        quaternion parameters, which must be pure quaternion arrays. If one
        quaternion parameter is given, the other is inferred as an array of
        zeros. If both are given, the quivers plotted start at the quaternion
        value represented by the first parameter and end at the values represented
        by the second.
    </para>
    <para>
        The <code>varargin</code> parameters are passed to the Matlab
        quiver3 function, and must therefore conform to the requirements of that
        function.
    </para>
    <para>
        The output parameter is optional, with the same functionality as
        the corresponding &matlab; function (a graphics handle).
    </para>
    <para>
        For more sophisticated requirements, use the Matlab function
        and pass the X, Y, Z, and U, V, W components of the quaternion array(s)
        as the first three or six parameters.
    </para>
</long>
<examples>
<precode>
>> quiver3(randv(1,128)); axis equal
</precode>
<para>
results in the creation of a plot similar to the following.
</para>
<figure>quiver.png</figure>
</examples>
<seealso>
<matlabfun name = "quiver3"/>
</seealso>
</function>

<!--$Id: quiver3.xml 1004 2017-11-15 17:14:09Z sangwine $-->

=== replab/replab/external/qtfm/helpfiles/xmlfiles/imag.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE function SYSTEM "qtfmfunction.dtd">
<function name = "imag" overload = "both">
<short>Imaginary part of a complex quaternion</short>
<syntax>Y = imag(X)</syntax>
<long>
<para>
<code>imag(X)</code> returns the imaginary part of a complex quaternion.
If <code>X</code> is a real quaternion, <code>imag(X)</code> returns zero.
</para>
<para>
The concept of the imaginary part of a quaternion should not be confused
with the vector part (returned by the function <code>vector</code> or
<code>v</code>).
</para>
</long>
<examples>
<precode>
>>  q =  complex(quaternion(1,2,3,4), quaternion(5,6,7,8))
 
q = (1+5i) + (2+6i) * I + (3+7i) * J + (4+8i) * K
 
>> imag(q)
 
ans = 5 + 6 * I + 7 * J + 8 * K
 
>> real(q)
 
ans = 1 + 2 * I + 3 * J + 4 * K
</precode>
</examples>
<seealso>
<matlabfun name = "imag"/>
<qtfmfun name = "real"/>
</seealso>
<references>
<reference>Ward, J. P., "Quaternions and Cayley numbers", Kluwer, 1997.</reference>
</references>
</function>

<!--$Id: imag.xml 1004 2017-11-15 17:14:09Z sangwine $-->

=== replab/replab/external/qtfm/helpfiles/xmlfiles/randq.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE function SYSTEM "qtfmfunction.dtd">
<function name = "randq" overload = "false">
<short>Uniformly distributed unit quaternions or rotations</short>
<syntax>Y = randq(varargin)</syntax>
<long>
<para>
<code>randq</code> constructs uniformly distributed quaternions (distributed
uniformly in 4-space). It accepts the same parameters as the &matlab;
functions <code>rand</code> and <code>randn</code>.
</para>
<para>
Each quaternion returned is the result of three calls on the &matlab; function
<code>rand</code>, and hence <code>randv</code> modifies the state of the
generator used by <code>rand</code>.
To initialise the generator or control the choice of generator, use
<code>rand</code>.
</para>
<para>
The result will have uniformly distributed axes and Gaussian-distributed
angles. This rather non-intuitive result is discussed by Shoemake (see
reference). If the quaternions supplied by this function are applied to a
constant pure quaternion (e.g. <code>qi</code>) using the formula
<code>conj(S) .* qi .* S</code>,
the result will be randomly oriented pure quaternions with a uniform
distribution in 3-space: this is what is meant by 'uniformly distributed
rotations' (but note that this result can be obtained more directly with
<code>randv</code> (q.v.)).
</para>
</long>
<examples>
<precode>
>> q = randq(2)
 
q = 2x2 quaternion array

>> angle(q)

ans =

    2.0598    2.0802
    1.1229    1.4153

>> abs(q)

ans =

     1     1
     1     1
</precode>
The Gaussian distribution of angles is easily demonstrated:
<precode>
>> q = randq(1e5,1)
 
q = 100000x1 quaternion array
 
>> hist(angle(q), 50)
</precode>
<figure>randq_angle_hist.png</figure>
</examples>
<seealso>
<matlabfun name = "rand"/>
<qtfmfun name = "randv"/>
</seealso>
<references>
<reference>Ken Shoemake, 'Uniform random rotations', in David Kirk (ed),
<italic>Graphics Gems III</italic>, Academic Press, 1992, pp124-132.
</reference>
</references>
</function>

<!--$Id: randq.xml 1004 2017-11-15 17:14:09Z sangwine $-->

=== replab/replab/external/qtfm/helpfiles/xmlfiles/normo.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE function SYSTEM "qtfmfunction.dtd">
<function name = "normo" overload = "false">
<short>Norm of an octonion</short>
<syntax>Y = normo(X)</syntax>
<long>
    <para>
        <italic>(Not to be confused with the function <code>norm</code>
        which computes a matrix norm.)</italic>
    </para>
<para>
<code>normo(X)</code> returns an array <code>Y</code> such that each
element of <code>Y</code> is the norm of the corresponding element of
<code>X</code>. The norm is the sum of the squares of the eight
components (seven components in the case where <code>X</code> is pure).
</para>
<para>
If <code>X</code> is a complex octonion, <code>normq(X)</code> returns
the complex semi-norm, computed in the same way.
The semi-norm of a complexified octonion can vanish. See the QTFM function
<code>normq</code> for references on this topic for quaternions.
No corresponding paper is known for the octonion case.
</para>
</long>
<examples>
<precode>
normo(octonion(1,1,1,1,1,1,1,1))

ans = 8
</precode>
<code>normo</code> is vectorized, and hence can operate on arrays.
It can also operate on complex octonions yielding a complex result in
general (the semi-norm):
<precode>
>> normo(1 + i + oi + on + om)

ans = 3.0000 + 2.0000i
</precode>
</examples>
<seealso>
<qtfmfun name = "abs"/>
<qtfmfun name = "norm"/>
</seealso>
</function>

<!--$Id: normo.xml 1004 2017-11-15 17:14:09Z sangwine $-->

=== replab/replab/external/qtfm/helpfiles/xmlfiles/length.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE function SYSTEM "qtfmfunction.dtd">
<function name = "length" overload = "both">
<short>Length of vector</short>
<syntax>Y = length(X)</syntax>
<long>
<para>
<code>length(X)</code> returns the number of quaternion elements in the
vector <code>X</code>.
</para>
</long>
<examples>
<precode>
>> q = randq(7,1)
 
q = 7x1 quaternion array
 
>> length(q)

ans = 7
</precode>
</examples>
<seealso>
<matlabfun name = "length"/>
</seealso>
</function>

<!--$Id: length.xml 1004 2017-11-15 17:14:09Z sangwine $-->
