=== replab/replab/external/qtfm/helpfiles/xmlfiles/qtfmfunction.dtd
<!-- Document type definition for QTFM function help document -->
<!-- (c) Stephen J. Sangwine and Nicolas Le Bihan, 2008 -->
<!--                                                          -->
<!-- See the file 'readme.txt' for information about how this -->
<!-- DTD file is used.                                        -->

<!ELEMENT function (short, syntax, long, examples?, seealso?, references?)>
<!ATTLIST function name      NMTOKEN #REQUIRED
                   overload (false | true | both) "false">

<!ENTITY  reg     '&#x00AE;'>
<!ENTITY  matlab "MATLAB&reg;">
<!ELEMENT short     (#PCDATA)><!-- Short description of QTFM function. -->
<!ELEMENT syntax    (#PCDATA)><!-- Typical calling syntax. -->

<!-- Description of what the function does. -->
<!ELEMENT long      (#PCDATA | para | figure | www)*>

<!ELEMENT examples  (#PCDATA | code | precode)*><!-- Command examples. -->
<!ELEMENT para      (#PCDATA | code | italic | bold | www)*>
<!ELEMENT code      (#PCDATA)><!-- Inline code snippet -->
<!ELEMENT precode   (#PCDATA)><!-- Preformatted code-->
<!ELEMENT figure    (#PCDATA)><!-- The image filename in the helpfiles directory -->
<!ELEMENT references (reference*)>
<!ELEMENT reference (#PCDATA | italic | bold | doi | www)*>
<!ELEMENT italic    (#PCDATA)>
<!ELEMENT bold      (#PCDATA)>
<!ELEMENT doi       (#PCDATA)><!-- A hyperlink to a DOI. -->
<!ELEMENT www       (#PCDATA)><!-- A hyperlink to a website. -->

<!-- Optional section with a list of related Matlab and/or QTFM functions. -->
<!ELEMENT seealso   (#PCDATA | matlabfun | qtfmfun)*>
<!-- Ideally, the next two should be constrained to legal function names only. -->
<!ELEMENT matlabfun EMPTY>
<!ATTLIST matlabfun name NMTOKEN #REQUIRED>
<!ELEMENT qtfmfun   EMPTY>
<!ATTLIST qtfmfun   name NMTOKEN #REQUIRED alias NMTOKEN #IMPLIED>
<!--$Id: qtfmfunction.dtd 1004 2017-11-15 17:14:09Z sangwine $-->

=== replab/replab/external/qtfm/helpfiles/xmlfiles/exp.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE function SYSTEM "qtfmfunction.dtd">
<function name = "exp" overload = "both">
<short>Exponential</short>
<syntax>Y = exp(X)</syntax>
<long>
<para>
<code>exp(X)</code> computes the exponential of its argument.
</para>
</long>
<examples>
<precode>
>> show(exp([qi, qj, qk]))
 
S = 0.5403    0.5403    0.5403

X = 0.8415         0         0

Y =      0    0.8415         0

Z =      0         0    0.8415
</precode>
</examples>
<seealso>
<matlabfun name = "exp"/>
<qtfmfun name = "axis"/>
<qtfmfun name = "angle"/>
<qtfmfun name = "log"/>
</seealso>
</function>

<!--$Id: exp.xml 1004 2017-11-15 17:14:09Z sangwine $-->

=== replab/replab/external/qtfm/helpfiles/xmlfiles/numel.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE function SYSTEM "qtfmfunction.dtd">
<function name = "numel" overload = "both">
<short>Number of elements in an array</short>
<syntax>Y = numel(X)</syntax>
<long>
    <para>
        <code>numel(X)</code> returns the number of quaternions or octonions in an
        array, just as the corresponding built-in &matlab; function does for other types.
    </para>
    <para>
        There is a complex history to this function, which is relevant only to code
        developed with versions of QTFM prior to 2.4 and versions of &matlab; prior
        to R2015b, when a new function <code>numArgumentsFromSubscript</code>
        was introduced into &matlab;. See the notes in the quaternion (not
        octonion) source file for
        information about this.
    </para>
</long>
<seealso>
<matlabfun name = "numel"/>
<qtfmfun name = "prod"/>
<qtfmfun name = "size"/>
</seealso>
</function>

<!--$Id: numel.xml 1004 2017-11-15 17:14:09Z sangwine $-->

=== replab/replab/external/qtfm/helpfiles/xmlfiles/norm.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE function SYSTEM "qtfmfunction.dtd">
<function name = "norm" overload = "both">
<short>Matrix or vector norm</short>
<syntax>Y = norm(X, p)</syntax>
<long>
<para><italic>See the function <code>normq</code> for the quaternion
norms of the elements of a matrix - this function computes a matrix
norm as does the &matlab; function of the same name.</italic>
</para>
<para>
<code>norm(X, p)</code> computes the norm of the vector or matrix <code>X</code>.
The second parameter selects the type of norm computed. Possible
values are 1, 2, inf, -inf, and 'fro'. The default if <code>p</code> is omitted
is 2.
</para>
<para>
If <code>X</code> is a vector the norms computed for each value of <code>p</code>
are as follows: 1 - sum of the absolute values; 2 - square root of the sum of
squared values; inf - maximum absolute value; -inf - minimum absolute value.
</para>
<para>
If <code>X</code> is a matrix the norms computed for each value of <code>p</code>
are as follows: 1 - sum of the absolute values of the elements of each
column; 2 - the largest singular value (requiring a singular value decomposition
to be computed); inf - maximum absolute value in
each column; 'fro' - the Frobenius norm.
</para>
</long>
<seealso>
<matlabfun name = "norm"/>
<qtfmfun name = "normq"/>
<qtfmfun name = "svd"/>
</seealso>
</function>

<!--$Id: norm.xml 1004 2017-11-15 17:14:09Z sangwine $-->

=== replab/replab/external/qtfm/helpfiles/xmlfiles/write.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE function SYSTEM "qtfmfunction.dtd">
<function name = "write" overload = "false">
<short>Output a quaternion array to a text file.</short>
<syntax>write(filename, format, a)</syntax>
<long>
<para>
This function writes a text file which is designed to be easily
read into other software.  The
first line of the file contains two integer values giving the
number of rows and columns in the file.  The quaternion values
then follow in raster order, that is with the column index varying
most rapidly. Each quaternion value occupies one line in the file,
and consists of four floating-point values, separated by spaces.
</para>
<para>
The format parameter may be omitted, in which case a default is
assumed which outputs sufficient digits to represent double values
with no loss of accuracy. Otherwise the format is a string (see the
standard &matlab; function <code>fprintf</code> for details).
</para>
<para>
If the parameter <code>a</code> is a pure quaternion, only three components
are written per quaternion.
</para>
<para>
The text file written by this function may be read by the matching function
<code>read</code>.
</para>
</long>
<examples>
<precode>
>> q = randq(2)
 
q = 2x2 quaternion array
 
>> show(q)
 
q.S =
 
    0.4196    0.2015
    0.2664   -0.5665

q.X =
 
    0.3533   -0.0095
    0.1953    0.3631

q.Y =
 
    0.8358    0.9786
   -0.8679   -0.3181

q.Z =
 
   -0.0225    0.0398
    0.3710    0.6679

>> write('data.txt', q)
</precode>
The resulting text file is as follows:
<precode>
       2        2
 +4.1963850834385363e-01  +3.5330836341397237e-01  +8.3580546214538765e-01  -2.2493379128557589e-02
 +2.0153918465836959e-01  -9.5148222156437885e-03  +9.7862378239152092e-01  +3.9836136147441963e-02
 +2.6635283946883026e-01  +1.9532770507814057e-01  -8.6792292331469123e-01  +3.7096233194312195e-01
 -5.6651136993926687e-01  +3.6311064121797937e-01  -3.1805954904022421e-01  +6.6787248276009414e-01
</precode>
</examples>
<seealso>
<matlabfun name = "fprintf"/>
<qtfmfun name = "read"/>
</seealso>
</function>

<!--$Id: write.xml 1004 2017-11-15 17:14:09Z sangwine $-->

=== replab/replab/external/qtfm/helpfiles/xmlfiles/mean.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE function SYSTEM "qtfmfunction.dtd">
<function name = "mean" overload = "both">
<short>Average or mean value</short>
<syntax>Y = mean(X, dim)</syntax>
<long>
<para>
<code>mean(X, dim)</code> computes the mean values of the elements of the
quaternion or octonion array <code>X</code> along dimension <code>dim</code>. If
omitted, <code>dim</code> defaults to the columns of <code>X</code>.
</para>
</long>
<examples>
<precode>
>> mean([qi, qj, qk])
 
ans = 0.3333 * I + 0.3333 * J + 0.3333 * K
</precode>
</examples>
<seealso>
<matlabfun name = "mean"/>
</seealso>
</function>

<!--$Id: mean.xml 1004 2017-11-15 17:14:09Z sangwine $-->

=== replab/replab/external/qtfm/helpfiles/xmlfiles/commutator.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE function SYSTEM "qtfmfunction.dtd">
<function name = "commutator" overload = "false">
<short>Commutator</short>
<syntax>C = commutator(X, Y, option)</syntax>
<long>
    <para>
        <code>C = commutator(X, Y)</code> returns <code>X .* Y - Y .* X</code> and
        <code>C = commutator(X, Y, 'diff')</code> returns the same result.
    </para>
    <para>
<code>C = commutator(X, Y, 'prod')</code> returns the quaternion
<code>c</code> that multiplies the product <code>X .* Y</code> on the right
to give the result of the product <code>Y .* X</code>.
</para>
</long>
<examples>
<precode>
>> x = randq; y = randq;
>> x .* y .* commutator(x, y, 'prod')

ans =

0.254 + 0.8994 * I + 0.313 * J + 0.169 * K

>> y .* x

ans =

0.254 + 0.8994 * I + 0.313 * J + 0.169 * K
</precode>
<para>
Reals commute so the commutator of any two reals will be zero: 
</para>
<precode>
>> commutator(randn, randn)

ans = 0
</precode>
</examples>
<seealso>
<qtfmfun name = "associator"/>
</seealso>
</function>

<!--$Id: commutator.xml 1004 2017-11-15 17:14:09Z sangwine $-->

=== replab/replab/external/qtfm/helpfiles/xmlfiles/svdj.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE function SYSTEM "qtfmfunction.dtd">
<function name = "svdj" overload = "false">
<short>Singular value decomposition using Jacobi algorithm</short>
<syntax>[U,S,V] = svdj(A, tol)</syntax>
<long>
<para>
<code>[U,S,V] = svdj(A, tol)</code> computes the quaternion singular value
decomposition of <code>A</code> using a Jacobi algorithm, with <code>tol</code>
as a tolerance to control the stopping point of the algorithm, which is
iterative.
</para>
<para>
This function is primarily provided for test and verification purposes,
since Jacobi algorithms are known to be accurate, although slow. For a
faster computation use the <code>svd</code> function.
</para>
<para>
This function will work for real and complex matrices, as well as quaternion
matrices. This makes possible verification of results using the <code>adjoint</code>
function, since by this means a complex matrix may be constructed from a
quaternion matrix and the singular values determined accurately. The code
also exhibits specialised techniques that allow the same code to work on
real, complex and quaternion data, which can be useful when developing
experimental algorithms.
</para>
</long>
<examples>The singular values of the complex adjoint are the same as those
of the quaternion matrix, but they occur in pairs because of the duplication
of information in the adjoint.
<precode>
>> q = randq(4)
 
q = 4x4 quaternion array
 
>> svdj(q)

ans =

    2.9641
    2.3497
    1.2075
    0.4849

>> svdj(adjoint(q))

ans =

    2.9641
    2.9641
    2.3497
    2.3497
    1.2075
    1.2075
    0.4849
    0.4849
</precode>
</examples>
<seealso>
<qtfmfun name = "svd"/>
<qtfmfun name = "adjoint"/>
</seealso>
<references>
<reference>N. Le Bihan and S. J. Sangwine,
'Jacobi Method for Quaternion Matrix Singular Value Decomposition',
<italic>Applied Mathematics and Computation</italic>,
<bold>187</bold> (2), 15 April 2007, 1265-1271.
<doi>10.1016/j.amc.2006.09.055</doi>.
</reference>
<reference>S. J. Sangwine and N. Le Bihan,
'Computing the SVD of a quaternion matrix', 
<italic>in</italic>
Seventh International Conference on Mathematics in Signal Processing,
17-20 December 2006, The Royal Agricultural College, Cirencester, UK,
pp5-8. Institute of Mathematics and its Applications, 2006.
</reference>
</references>
</function>



<!--$Id: svdj.xml 1004 2017-11-15 17:14:09Z sangwine $-->

=== replab/replab/external/qtfm/helpfiles/xmlfiles/blkdiag.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE function SYSTEM "qtfmfunction.dtd">
<function name = "blkdiag" overload = "true">
<short>Construct block diagonal matrix from input arguments.</short>
<syntax>R = blkdiag(varargin)</syntax>
<long>
<para>
Given a number of quaternion matrices, <code>blkdiag</code> builds a block
diagonal matrix with the given matrices on the diagonal. It works exactly
as the overloaded &matlab; function. The matrices supplied are not required
to have the same size.
</para>
</long>
<examples>
<precode>
>> blkdiag(randq(2), randq(3))
 
ans =
 
     5x5 quaternion array
 
>> s(ans)

ans =

    0.0058    0.7714         0         0         0
   -0.1470   -0.4792         0         0         0
         0         0   -0.5044    0.5444   -0.5741
         0         0    0.3300    0.8763    0.0667
         0         0   -0.0868    0.9223    0.6933
</precode>
</examples>
<seealso>
<qtfmfun name = "diag"/>
<qtfmfun name = "horzcat"/>
<qtfmfun name = "vertcat"/>
<matlabfun name = "blkdiag"/>
</seealso>
</function>

<!--$Id: blkdiag.xml 1004 2017-11-15 17:14:09Z sangwine $-->
